version: 2

project_name: dca

before:
  hooks:
    - go mod tidy

builds:
  - id: dca
    main: ./cmd/dca
    binary: dca
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

brews:
  - name: dca
    repository:
      owner: ulfschnabel
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/ulfschnabel/dca
    description: "Discord CLI for Agents - Feature-complete Discord automation"
    license: MIT
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: ulfschnabel
    name: dca
  draft: false
  prerelease: auto
